!{Katyusha V1.2 - Desenvolvida por Ruan "Kotovich" Barros}!
!{Katyusha - moya pravda lyubit}!
!{	Caracter de desculpa - :}	}!

!{Eventos Expressos (Que precisam ser executados primeiro)}!

{contem->}porra<#><A>{fale->}Ah! que mal educado! >:(
{contem->}caralho<#><A>{fale->}Não falo com mal educados! >:(
{contem->}fdp<#><A>{fale->}Não falo com mal educados! >:(
{contem->}porn<#><A>{fale->}Eu não creio! >:(
{contem->}penis<#><A>{fale->}Eu não creio! >:(
