/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mild.katyusha.system.window;

import java.awt.AWTException;
import java.awt.Color;
import java.awt.Robot;
import java.awt.Toolkit;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.StringSelection;
import java.awt.event.KeyEvent;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import mild.katyusha.system.build.TRDBundle;
import mild.katyusha.system.ctr.CTRInteligencia;
import mild.katyusha.system.ctr.CTRRotulo;
import mild.katyusha.system.datatype.ACAOFalar;
import mild.katyusha.system.datatype.Acao;
import mild.katyusha.system.datatype.Cognicao;
import mild.katyusha.system.bean.JTransparentLabel;
import mild.katyusha.system.bean.JTransparentPanel;
import mild.katyusha.system.datatype.Twig;

/**
 *
 * @author Dmitry
 */
public class WNDBundle extends JDialog {

    public boolean isActivated = true;
    public boolean isReady = false;
    public Thread thread;
    public CTRInteligencia cerebro;
    public boolean isSad = false;
    public ArrayList<Twig> menus = new ArrayList<>();
    CTRRotulo cTRRotulo;
    public WNDOpener caller = null;
    public boolean autoMenu = false;
    public String ultimo = "";

    public synchronized boolean isIsReady() {
        return isReady;
    }

    public synchronized void setIsReady(boolean isReady) {
        this.isReady = isReady;
    }

    @Override
    public String toString() {
        return "{" + getName() + "}";
    }

    public boolean isIsActivated() {
        return isActivated;
    }

    public void setActivated(boolean isActivated) {
        this.isActivated = isActivated;
    }

    public void restart() {
        this.dispose();
        if (caller != null) {
            caller.dispose();
        }
        System.runFinalization();
        System.gc();
        java.awt.EventQueue.invokeLater(() -> {
            new WNDBundle().setVisible(true);
        });
    }

    public WNDBundle() {
        initComponents();
        jTcopiado.setVisible(false);
        kLoad.setVisible(false);
        jTrotulo.setVisible(false);
        cTRRotulo = new CTRRotulo(this);
        for (Object obj : jPainelMenu.getComponents()) {
            if (obj instanceof Twig) {
                Twig objeto = (Twig) obj;
                objeto.addMouseListener(cTRRotulo);
                menus.add(objeto);
            }
        }
        CTRInteligencia.addTwigs(menus);
        jPainelMenu.setVisible(false);
        this.cerebro = new CTRInteligencia(this);
        this.dispose();
        this.setLocationRelativeTo(null);
        this.setLocation(this.getX(), 0);
        //this.setOpacity(0.9f);
        this.setUndecorated(true);
        this.setSize(jPanel1.getSize());
        repaint();
        jLbKatyusha.grabFocus();
        //controle = new CTRGlobal(this);
        this.setFocusableWindowState(true);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.setVisible(false);
        iniciarFala();
    }

    public void pointOnTextField() {
        try {
            new Robot().mouseMove(Toolkit.getDefaultToolkit().getScreenSize().width / 2, jInputText.getY() + jInputText.getHeight() / 2);
            new Robot().mousePress(MouseEvent.BUTTON1_DOWN_MASK);
            new Robot().mouseRelease(MouseEvent.BUTTON1_DOWN_MASK);
            jInputText.grabFocus();
        } catch (AWTException ex) {
            Logger.getLogger(WNDBundle.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void iniciarFala() {
        List<Acao> action = new ArrayList<>();
        ACAOFalar acaoFalar = new ACAOFalar();
        acaoFalar.setCaller(this);
        acaoFalar.setObjeto("Oiiii :D");
        action.add(acaoFalar);
        Cognicao cognicao = new Cognicao();
        cognicao.setAcoes(action);
        cerebro.executarCognicao(cognicao);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        kLoad = new javax.swing.JPanel();
        jLoad = new javax.swing.JLabel();
        jLoadBar = new javax.swing.JProgressBar();
        jPanel4 = new javax.swing.JPanel();
        jPainelMenu = new JTransparentPanel(0.7f);
        jI2 = new Twig();
        jI1 = new Twig();
        jI3 = new Twig();
        jI4 = new Twig();
        jI5 = new Twig();
        jI7 = new Twig();
        jI6 = new Twig();
        jTrotulo = new JTransparentLabel(0.7f);
        jPanel5 = new JTransparentPanel(0.7f);
        jLbPainel = new javax.swing.JLabel();
        jLbFrente = new JTransparentLabel(0.45f);
        jLbKatyusha = new javax.swing.JLabel();
        jInputText = new javax.swing.JTextField();
        jTcopiado = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jOutputText = new javax.swing.JTextArea();

        setAlwaysOnTop(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                formMouseMoved(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formMouseExited(evt);
            }
        });

        jPanel2.setOpaque(false);
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanel2MouseMoved(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel2MouseExited(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 0, 0));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 0, 51), 4, true));
        jPanel1.setPreferredSize(new java.awt.Dimension(700, 50));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel1MouseExited(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kLoad.setOpaque(false);

        jLoad.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLoad.setForeground(new java.awt.Color(255, 255, 255));
        jLoad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLoad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mild/katyusha/system/gfx/kload.gif"))); // NOI18N
        jLoad.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLoad.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLoad.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jLoadBar.setForeground(new java.awt.Color(153, 0, 204));
        jLoadBar.setToolTipText("");

        javax.swing.GroupLayout kLoadLayout = new javax.swing.GroupLayout(kLoad);
        kLoad.setLayout(kLoadLayout);
        kLoadLayout.setHorizontalGroup(
            kLoadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kLoadLayout.createSequentialGroup()
                .addGroup(kLoadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLoad)
                    .addComponent(jLoadBar, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 7, Short.MAX_VALUE))
        );
        kLoadLayout.setVerticalGroup(
            kLoadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kLoadLayout.createSequentialGroup()
                .addComponent(jLoad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLoadBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(kLoad, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 60, 80));

        jPanel4.setOpaque(false);
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPainelMenu.setBackground(new Color(100,50,50));
        jPainelMenu.setBorder(new javax.swing.border.LineBorder(new Color(255,100,100), 3, true));
        jPainelMenu.setPreferredSize(new java.awt.Dimension(314, 48));

        jI2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mild/katyusha/system/gfx/menu/pasta.png"))); // NOI18N
        jI2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jI1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mild/katyusha/system/gfx/menu/pasta.png"))); // NOI18N
        jI1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jI3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mild/katyusha/system/gfx/menu/pasta.png"))); // NOI18N
        jI3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jI4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mild/katyusha/system/gfx/menu/pasta.png"))); // NOI18N
        jI4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jI5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mild/katyusha/system/gfx/menu/pasta.png"))); // NOI18N
        jI5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jI7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mild/katyusha/system/gfx/menu/pasta.png"))); // NOI18N
        jI7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jI6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mild/katyusha/system/gfx/menu/pasta.png"))); // NOI18N
        jI6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPainelMenuLayout = new javax.swing.GroupLayout(jPainelMenu);
        jPainelMenu.setLayout(jPainelMenuLayout);
        jPainelMenuLayout.setHorizontalGroup(
            jPainelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPainelMenuLayout.createSequentialGroup()
                .addComponent(jI1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jI2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jI3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jI4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jI5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jI6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jI7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPainelMenuLayout.setVerticalGroup(
            jPainelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jI2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jI1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jI3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jI5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jI4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jI7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jI6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel4.add(jPainelMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 310, -1));

        jTrotulo.setBackground(new Color(100,70,70));
        jTrotulo.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jTrotulo.setForeground(new java.awt.Color(255, 102, 255));
        jTrotulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTrotulo.setText("Arquivo");
        jTrotulo.setBorder(new javax.swing.border.LineBorder(new Color(255,100,100), 3, true));
        jTrotulo.setOpaque(true);
        jPanel4.add(jTrotulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 310, 20));

        jPanel5.setOpaque(false);

        jLbPainel.setBackground(new Color(100,50,50));
        jLbPainel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLbPainel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mild/katyusha/system/gfx/menu/triforce.png"))); // NOI18N
        jLbPainel.setBorder(new javax.swing.border.LineBorder(new Color(255,100,100), 3, true));
        jLbPainel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLbPainel.setOpaque(true);
        jLbPainel.setPreferredSize(new java.awt.Dimension(48, 48));
        jLbPainel.setRequestFocusEnabled(false);
        jLbPainel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLbPainelMouseDragged(evt);
            }
        });
        jLbPainel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLbPainelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLbPainelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLbPainelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLbPainelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLbPainelMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLbPainel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLbPainel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 390, 80));

        jLbFrente.setBackground(new java.awt.Color(255, 153, 0));
        jLbFrente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLbFrente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mild/katyusha/system/gfx/neve.gif"))); // NOI18N
        jPanel1.add(jLbFrente, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 410, 220));

        jLbKatyusha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mild/katyusha/system/gfx/hp_1.png"))); // NOI18N
        jPanel1.add(jLbKatyusha, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 25, -1, -1));

        jInputText.setBackground(new Color(255,100,100));
        jInputText.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jInputText.setForeground(new java.awt.Color(102, 0, 0));
        jInputText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jInputText.setBorder(javax.swing.BorderFactory.createLineBorder(new Color(100,50,50), 3));
        jInputText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jInputTextActionPerformed(evt);
            }
        });
        jInputText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jInputTextKeyPressed(evt);
            }
        });
        jPanel1.add(jInputText, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 4, 400, 20));

        jTcopiado.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTcopiado.setForeground(new java.awt.Color(51, 0, 102));
        jTcopiado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTcopiado.setText("Copiado");
        jPanel1.add(jTcopiado, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 390, 50));

        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jOutputText.setEditable(false);
        jOutputText.setBackground(new Color(255,190,190));
        jOutputText.setColumns(20);
        jOutputText.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jOutputText.setForeground(new java.awt.Color(102, 0, 102));
        jOutputText.setLineWrap(true);
        jOutputText.setRows(3);
        jOutputText.setWrapStyleWord(true);
        jOutputText.setBorder(javax.swing.BorderFactory.createLineBorder(new Color(100,50,50), 3));
        jOutputText.setFocusable(false);
        jOutputText.setVerifyInputWhenFocusTarget(false);
        jOutputText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jOutputTextMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jOutputTextMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jOutputTextMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jOutputText);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 256, 400, 57));

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 408, 317));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseExited
        if (evt.getYOnScreen() >= jPanel1.getHeight()/2) {
            if (isActivated && evt.getY() >= 50) {
                thread = new Thread(new TRDBundle(this));
                thread.start();
            }
        }
    }//GEN-LAST:event_jPanel1MouseExited

    private void formMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseExited

    }//GEN-LAST:event_formMouseExited

    private void jInputTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jInputTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jInputTextActionPerformed

    private void jInputTextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jInputTextKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_UP && !(jInputText.getText().contains("Interpretando..."))) {
            jInputText.setText(ultimo);
        }
        if (evt.getKeyCode() == KeyEvent.VK_ENTER && !(jInputText.getText().contains("Interpretando..."))) {
            ultimo = jInputText.getText();
            send();
        }
    }//GEN-LAST:event_jInputTextKeyPressed

    public void send() {
        String comando = jInputText.getText();
        jOutputText.setText("Katyusha : Humm...");
        new Thread(()->{cerebro.enviarComando(comando);}).start();
    }

    private void jPanel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseExited

    }//GEN-LAST:event_jPanel2MouseExited

    private void formMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseMoved

    }//GEN-LAST:event_formMouseMoved

    private void jPanel2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseMoved

    }//GEN-LAST:event_jPanel2MouseMoved

    private void jLbPainelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbPainelMouseClicked
        if (!evt.isControlDown()) {
            if (evt.getButton() == MouseEvent.BUTTON3) {
                if (!jPainelMenu.isVisible()) {
                    if (this.autoMenu) {
                        jLbPainel.setIcon(new ImageIcon(this.getClass().getResource("/mild/katyusha/system/gfx/menu/triforce.png")));
                        this.autoMenu = false;
                    } else {
                        jLbPainel.setIcon(new ImageIcon(this.getClass().getResource("/mild/katyusha/system/gfx/menu/triforce_auto.png")));
                        this.autoMenu = true;
                    }
                }
            } else if (!this.autoMenu) {
                toggleMenu();
            }
        }
    }//GEN-LAST:event_jLbPainelMouseClicked

    private void jLbPainelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbPainelMouseDragged

    }//GEN-LAST:event_jLbPainelMouseDragged

    private void jLbPainelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbPainelMouseEntered
        if (autoMenu) {
            toggleMenu();
        }
    }//GEN-LAST:event_jLbPainelMouseEntered

    private void jLbPainelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbPainelMouseExited
        if (autoMenu) {
            toggleMenu();
        }
    }//GEN-LAST:event_jLbPainelMouseExited

    private void jOutputTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jOutputTextMouseClicked

    }//GEN-LAST:event_jOutputTextMouseClicked

    private void jOutputTextMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jOutputTextMousePressed

    }//GEN-LAST:event_jOutputTextMousePressed

    private void jOutputTextMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jOutputTextMouseReleased

    }//GEN-LAST:event_jOutputTextMouseReleased

    private void jLbPainelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbPainelMouseReleased
        jTcopiado.setVisible(false);
        jOutputText.setBackground(new Color(255, 190, 190));


    }//GEN-LAST:event_jLbPainelMouseReleased

    private void jLbPainelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbPainelMousePressed
        if (evt.isControlDown()) {
            Clipboard clipboard = Toolkit.getDefaultToolkit().getSystemClipboard();
            clipboard.setContents(new StringSelection(jOutputText.getText()), null);
            jTcopiado.setVisible(true);
            jOutputText.setBackground(new Color(155, 90, 90));
        }
    }//GEN-LAST:event_jLbPainelMousePressed

    private void toggleMenu() {
        if (jPainelMenu.isVisible()) {
            if (autoMenu) {
                jLbPainel.setIcon(new ImageIcon(this.getClass().getResource("/mild/katyusha/system/gfx/menu/triforce_auto.png")));
            } else {
                jLbPainel.setIcon(new ImageIcon(this.getClass().getResource("/mild/katyusha/system/gfx/menu/triforce.png")));
            }
            jPainelMenu.setVisible(false);
        } else {
            if (autoMenu) {
                jLbPainel.setIcon(new ImageIcon(this.getClass().getResource("/mild/katyusha/system/gfx/menu/triforce_2_auto.png")));
            } else {
                jLbPainel.setIcon(new ImageIcon(this.getClass().getResource("/mild/katyusha/system/gfx/menu/triforce_2.png")));
            }
            jPainelMenu.setVisible(true);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            new WNDBundle().setVisible(true);
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jI1;
    private javax.swing.JLabel jI2;
    private javax.swing.JLabel jI3;
    private javax.swing.JLabel jI4;
    private javax.swing.JLabel jI5;
    private javax.swing.JLabel jI6;
    private javax.swing.JLabel jI7;
    public javax.swing.JTextField jInputText;
    public javax.swing.JLabel jLbFrente;
    public javax.swing.JLabel jLbKatyusha;
    private javax.swing.JLabel jLbPainel;
    public javax.swing.JLabel jLoad;
    public javax.swing.JProgressBar jLoadBar;
    public javax.swing.JTextArea jOutputText;
    public javax.swing.JPanel jPainelMenu;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jTcopiado;
    public javax.swing.JLabel jTrotulo;
    public javax.swing.JPanel kLoad;
    // End of variables declaration//GEN-END:variables

}
