/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mild.katyusha.system.window;

import java.awt.event.KeyEvent;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.io.PrintWriter;
import java.math.BigInteger;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Dmitry
 */
public class WNDUsing extends JFrame {

    /**
     * Creates new form WNDOpen
     */
    private String passwords[] = {"1f3l53", "f0r34ch", "b3r53k", "c4mm0", "45p1r1n", "gunb4ll", "m4l0ch", "k4l45h", "3ch0", "r3v3rb", "b455", "m1ddl3", "th1ck", "th1n", "bl355", "m355", "p1zz4", "c4rt00n", "5vgdr4g", "5l33p", "h0ll0w", "pr3c10u5", "pr0t3ct", "fl4t", "51m10", "c3z4r", "h0m35h", "kh4n", "md5d1g", "mudv", "mu5h"};
    int tri = 0;
    
    private String digerirMensagem(String str) {
        
        MessageDigest md = null;
        try {
            md = MessageDigest.getInstance("MD5");
        } catch (NoSuchAlgorithmException ex) {
            Logger.getLogger(WNDUsing.class.getName()).log(Level.SEVERE, null, ex);
        }
        BigInteger hash = new BigInteger(1, md.digest(str.getBytes()));
        return hash.toString(16);
    }
    
    public WNDUsing() {
        this.setVisible(false);
        File arquivo = new File("key.k");
        int senia = Integer.parseInt(new SimpleDateFormat("dd").format(new Date()));
        if (arquivo.exists()) {
            if (digerirMensagem(passwords[senia - 1]).equals(lerKey())) {
                this.dispose();
                new WNDLoad().setVisible(true);
            } else {
                if (arquivo.delete()) {
                    initKey();
                } else {
                    JOptionPane.showMessageDialog(null, "Arquivo 'key.k' não pôde ser excluído, delete-o manualmente", "Erro", JOptionPane.ERROR_MESSAGE);
                    System.exit(0);
                }
            }
        } else {
            initKey();
        }
        
    }
    
    private void initKey() {
        initComponents();
        this.setVisible(true);
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);
        this.setTitle("Katyusha V1.6 - Password");
        this.setIconImage(new ImageIcon(this.getClass().getResource("/mild/katyusha/system/gfx/charged.gif")).getImage());
        this.setLocationRelativeTo(null);
        jPasswordField2.grabFocus();
    }
    
    private String lerKey() {
        String key = "null";
        try {
            BufferedReader bufferedReader = new BufferedReader(new FileReader("key.k"));
            if (bufferedReader.ready()) {
                key = bufferedReader.readLine();
                bufferedReader.close();
            }
        } catch (FileNotFoundException ex) {
            System.out.println(ex);
        } catch (IOException ex) {
            System.out.println(ex);
        }
        return key;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPasswordField2 = new javax.swing.JPasswordField();
        jPanel2 = new javax.swing.JPanel();
        try3 = new javax.swing.JLabel();
        try1 = new javax.swing.JLabel();
        try2 = new javax.swing.JLabel();

        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(102, 0, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Senha de Acesso :");

        jPasswordField2.setBackground(new java.awt.Color(102, 0, 0));
        jPasswordField2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPasswordField2.setForeground(new java.awt.Color(255, 255, 255));
        jPasswordField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPasswordField2.setBorder(null);
        jPasswordField2.setEchoChar('\u25ca');
        jPasswordField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordField2KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jPasswordField2KeyReleased(evt);
            }
        });

        jPanel2.setOpaque(false);

        try3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mild/katyusha/system/gfx/try.png"))); // NOI18N

        try1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mild/katyusha/system/gfx/try.png"))); // NOI18N

        try2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mild/katyusha/system/gfx/try.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(try1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(try2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(try3)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(try1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(try2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(try3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPasswordField2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPasswordField2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField2KeyReleased

    }//GEN-LAST:event_jPasswordField2KeyReleased

    private void jPasswordField2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField2KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            tri++;
            int data = 0;
            String pass = new String(jPasswordField2.getPassword());
            try {
                data = Integer.parseInt(new SimpleDateFormat("dd").format(new Date()));
            } catch (Exception ex) {
                System.out.println(ex);
            }
            if (passwords[data - 1].equals(pass)) {
                try {
                    PrintWriter printWriter = new PrintWriter(new File("key.k"));
                    printWriter.write(digerirMensagem(pass));
                    printWriter.close();
                    this.dispose();
                    new WNDLoad().setVisible(true);
                } catch (FileNotFoundException ex) {
                    System.out.println(ex);
                }
            } else {
                jPasswordField2.setText("");
                switch (tri) {
                    case 1:
                        try3.setVisible(false);
                        JOptionPane.showMessageDialog(null, "Senha Incorreta.", "Erro", JOptionPane.ERROR_MESSAGE);
                        break;
                    case 2:
                        try2.setVisible(false);
                        JOptionPane.showMessageDialog(null, "Senha Incorreta, de novo!", "Erro", JOptionPane.ERROR_MESSAGE);
                        break;
                    case 3:
                        try1.setVisible(false);
                        JOptionPane.showMessageDialog(null, "Senha Incorreta, encerrando...", "Erro", JOptionPane.ERROR_MESSAGE);
                        System.exit(0);
                        break;
                    default:
                        System.exit(0);
                        break;
                }
            }
        }
    }//GEN-LAST:event_jPasswordField2KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WNDUsing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WNDUsing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WNDUsing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WNDUsing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new WNDUsing();
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JLabel try1;
    private javax.swing.JLabel try2;
    private javax.swing.JLabel try3;
    // End of variables declaration//GEN-END:variables
}
